SMS_Stored/Controllers/AllocationController.cs
using Microsoft.AspNetCore.Mvc;
using SMS.BL.Allocation.Interface;

using SMS.ViewModel.Allocation;
using SMS.ViewModel.AllocationViewModel;
using SMS.ViewModel.ErrorResponse;
using SMS.ViewModel.RepositoryResponse;
using SMS.ViewModel.StaticData;

using Microsoft.AspNetCore.Mvc.Rendering;
using SMS.Model.Teacher_Subject_Allocation;
using NuGet.Protocol.Core.Types;
using SMS.Model.Student_Subject_Teacher_Allocation;
using System.Collections.Generic;


namespace SMS_Stored.Controllers
{
    public class AllocationController : Controller
    {
        private readonly IAllocationRepository _allocationRepository;
        private readonly ILogger<AllocationController> _logger;

        public AllocationController(IAllocationRepository allocationRepository, ILogger<AllocationController> logger)
        {
            _allocationRepository = allocationRepository;
            _logger = logger;
        }
        /// <summary>
        /// index page of subject allocation
        /// </summary>
        /// <returns></returns>
        public IActionResult SubjectAllocation()
        {
           return View();
        }
        /// <summary>
        /// Index page of student alloctaion
        /// </summary>
        /// <returns></returns>
        public IActionResult StudentAllocation()
        {
            return View();
        }
        /// <summary>
        /// Get all subject allocation
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetSubjectAllocations()
        {
            var errorResponse = new ErrorResponse();
            try
            {
                _logger.LogInformation("GetSubjectAllocations method called");
                var response = _allocationRepository.GetAllSubjectAllocations();

                if (response.Success && response.Data != null && response.Data.Any())
                {
                    return PartialView("_SubjectAllocationList", response.Data);
                }
                else
                {
                    errorResponse.Messages.Add("No data available or failed to retrieve data.");
                    if (response.Messages.Any())
                    {
                        errorResponse.Messages.AddRange(response.Messages);
                    }
                    return Json(new { success = false, messages = errorResponse.Messages });
                }
            }
            catch (Exception ex)
            {              
                _logger.LogError(ex, "Error occurred while getting subject allocations");
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Subject Allocations"));
                return Json(new { success = false, messages = errorResponse.Messages });
            }
        }
        /// <summary>
        /// Add or edit subject allocation
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult UpsertSubjectAllocation(long id = 0)
        {
            ViewBag.TeacherList = new SelectList(_allocationRepository.GetEnabledTeachersList(), "Value", "Text");
            ViewBag.SubjectList = new SelectList(_allocationRepository.GetEnabledSubjectList(), "Value", "Text");

            if (id == 0)
            {
                return PartialView("_UpsertTeacherSubjectAllocation", new Teacher_Subject_AllocationBO());
            }
            else
            {
                var subjectAllocation = _allocationRepository.GetSubjectAllocationById(id);
                if (subjectAllocation == null)
                {
                    return NotFound();
                }
                return PartialView("_UpsertTeacherSubjectAllocation", subjectAllocation);
            }
        }

        /// <summary>
        /// Add or edit
        /// </summary>
        /// <param name="subjectAllocation"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertSubjectAllocation(Teacher_Subject_AllocationBO subjectAllocation)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var response = _allocationRepository.UpsertSubjectAllocation(subjectAllocation);

                    return Json(new { success = response.Success, message = string.Join(", ", response.Messages) });
                }
                catch (Exception ex)
                {
                    return Json(new { success = false, message = $"An error occurred while processing the request: {ex.Message}" });
                }
            }
            else
            {
                var errors = ModelState
                    .Where(ms => ms.Value.Errors.Any())
                    .Select(ms => new
                    {
                        Key = ms.Key,
                        Errors = ms.Value.Errors.Select(e => e.ErrorMessage).ToArray()
                    });

                return Json(new { success = false, errors });
            }
        }
        /// <summary>
        /// Delete subject allocation
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteSubjectAllocation(long id)
        {
            var errorResponse = new ErrorResponse();

            try
            {
                _logger.LogInformation("DeleteSubject method called to delete subject with ID: {ID}", id);
                var response = new RepositoryResponse<bool>();

                response = _allocationRepository.DeleteSubjectAllocation(id);

                if (response.Success)
                {
                    return Json(new { success = true, message = response.Messages });
                }
                else
                {
                    _logger.LogWarning("Delete method called to delete subjectallocation with ID: {ID}", id);

                    return Json(new { success = false, message = response.Messages });
                }

            }
            catch
            {
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Delete_Data, "Subjects Allocation"));

                return Json(new { success = errorResponse.Success, message = errorResponse.ErrorMessages });
            }
        }
        /// <summary>
        /// Search subject allocation
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SearchSubjectAllocation(SearchViewModel model)
        {
            var errorResponse = new ErrorResponse();
            try
            {
                var response = _allocationRepository.SearchSubjectAllocations(model);
                if (response.Success && response.Data != null && response.Data.Any())
                {

                    return PartialView("_SubjectAllocationList", response.Data);
                }
                else
                {
                    _logger.LogError("No allocations found");
                    return Json(new { success = false, message = response.Messages });
                }

            }
            catch
            {
                _logger.LogError("Error in search allocations");
                errorResponse.Messages.Add(string.Format(StaticMessages.Data_Not_Found));
                // errorResponse.Messages.Add(ex.Message); 

                return Json(new { success = false, message = errorResponse.Messages });
            }
        }
        /******************************************************************Student Allocation*******************************************************/
        /// <summary>
        /// Get all student allocations
        /// </summary>
        /// <param name="status"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetStudentAllocations(string status = "all")
        {
            var errorResponse = new ErrorResponse();
            try
            {
                //var response =  new RepositoryResponse<IEnumerable<StudentAllocationGroupedViewModel>>();
                bool ? isEnabled = null;
                if (status.ToLower() == "active")
                {
                    isEnabled = true;
                }
                else if (status.ToLower() == "inactive")
                {
                    isEnabled = false;
                }
                 var response = _allocationRepository.GetAllStudentAllocations(isEnabled);
                if (response.Success && response.Data != null && response.Data.Any())
                {
                    
                    return PartialView("_StudentAllocationList", response.Data);
                }
                else
                {
                    errorResponse.Messages.Add(string.Format(response.Messages.ToString()));
                    return new JsonResult(errorResponse);
                }
            }
            catch (Exception ex)
            {
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Students Allocation"));
                return new JsonResult(new { success = errorResponse.Success, message = errorResponse.ErrorMessages });
            }
        }
        /// <summary>
        /// Add student allocation
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult AddStudentAllocation(long id = 0)
        {
            ViewBag.TeacherList = new SelectList(_allocationRepository.GetTeacherListFromAllocation(), "Value", "Text");
            ViewBag.SubjectList = new SelectList(_allocationRepository.GetAllSubjectsFromAllocation(), "Value", "Text");
            ViewBag.StudentList = new SelectList(_allocationRepository.GetEnabledStudentList(), "Value", "Text");
            if (id == 0)
            {

SMS_Stored/Views/Allocation/StudentAllocation.cshtml
@model SMS.ViewModel.Allocation.StudentAllocationGroupedViewModel
@{
    ViewBag.Title = "Subject";

}
<link href="~/css/modulestylesheet.css" rel="stylesheet" />

<div class="card panel-default">
    <div class="panel-heading">
        <h2 class="card-header">Student Allocation</h2>
    </div>

    <div class="panel-body card-body">
        <div class="controls-container row">
            <div class="col-md-6">
                <a class="btn btn-outline-primary" style="margin: 10px; background-color: #cbf5ee;" onclick="LoadCreatePage()" id="button"> <i class="bi bi-plus"></i>  Add New Subject</a>

             @*    <a href="@Url.Action("ExportToExcel", "Subject")" class="btn btn-outline-primary" style="margin: 10px; background-color: #cbf5ee;">Download Excel<i class="bi bi-file-excel"></i> </a>
                <a href="@Url.Action("ExportToPdf", "Subject", new { status = "all" })" class="btn btn-outline-primary" style="margin: 10px; background-color: #cbf5ee;">Download PDF <i class="bi bi-file-pdf"></i></a> *@
            </div>


            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-8">
                        <div id="filterView">
                             @await Html.PartialAsync("_StudentAllocationFilterView") 
                        </div>
                    </div>
                    <div class="col-md-4 justify-content-end">
                        <div class="searchForm">
                            @await Html.PartialAsync("_StudentAllocationSearchView")
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="studentsAllocationList">
            @await Html.PartialAsync("_StudentAllocationList", Model)
        </div>

    </div>
</div>

<div class="col-md-4" id="createoredit">
    <!--Partial view-->
</div>


@section scripts {
    <script src="~/js/studentAllocation.js" asp-append-version="true"></script>
}

SMS_Stored/Views/Allocation/SubjectAllocation.cshtml
@model IEnumerable<SMS.ViewModel.Allocation.SubjectAllocationDetailViewModel>
@{
    ViewBag.Title = "SubjectAllocation";
}


<link href="~/css/modulestylesheet.css" rel="stylesheet" />
<style>

    #subjectAllocationList_wrapper {
        max-width: 800px;
        margin: 0 auto;
    }
</style>
<div class="card panel-default">
    <div class="panel-heading">
        <h2 class="card-header">Subject Allocation</h2>
    </div>
    <div class="panel-body card-body">

        <div class="controls-container">
            <a class="btn btn-outline-primary" style="margin: 10px; background-color: #cbf5ee;" onclick="LoadCreatePage()" id="button"> <i class="bi bi-plus"></i>  Add New Allocation</a>

            <div class="search-container">
                <div class="searchForm">
                    @await Html.PartialAsync("_SubjectAllocationSearchView")
                </div>
            </div>

        </div>

        <div id="subjectsAllocationList">
            @await Html.PartialAsync("_SubjectAllocationList",Model)
        </div>
    </div>
</div>
@*<button id="back-to-list" class="btn m-4" onclick="LoadList()" style="display: none;">Back</button>*@
<div class="col-md-4" id="createoredit">
    <!--Partial view-->


</div>

@section scripts {
   
    <script src="~/js/subjectAllocation.js" asp-append-version="true"></script>
}

SMS_Stored/Views/Allocation/_AddStudentAllocation.cshtml
@model SMS.Model.Student_Subject_Teacher_Allocation.Student_Subject_Teacher_AllocationBO

@{
    ViewBag.Title = "AddStudentAllocation";
}

<form id="studentAllocationForm" asp-action="AddStudentAllocation" asp-controller="Allocation" method="post" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#createoredit">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.StudentAllocationID)
    @Html.HiddenFor(model => model.SubjectAllocationID)

    <div class="container d-flex justify-content-center align-items-center w-100 m-2" style="min-height: calc(100vh - 100px); margin-bottom: 50px;">
        <div class="card p-4 fr-div" style="max-width: 500px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1); border-radius: 10px;">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row form-group d-flex">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.StudentID, "Select Student", new { @class = "control-label required" })
                </div>
                <div class="col-md p-2">
                    @Html.DropDownListFor(model => model.StudentID, ViewBag.StudentList as SelectList, "Select Student", new { @class = "form-select dropdown", id = "studentDropdown" })
                    @Html.ValidationMessageFor(model => model.StudentID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row form-group d-flex">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.SubjectAllocationID, "Select Subject", new { @class = "control-label required" })
                </div>
                <div class="col-md p-2">
                    @Html.DropDownListFor(model => model.SubjectAllocationID, ViewBag.SubjectList as SelectList, "Select Subject", new { @class = "form-select", id = "subjectDropdown" })
                    @Html.ValidationMessageFor(model => model.SubjectAllocationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row form-group d-flex">
                <div class="col-md-4">
                    @Html.Label("Teacher", "Select Teacher", new { @class = "control-label required" })
                </div>
                <div class="col-md p-2">
                    <select id="teacherDropdown" class="form-select" name="SubjectAllocationID">
                        <option value="">Select Teacher</option>
                    </select>
                    @Html.ValidationMessageFor(model => model.SubjectAllocationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group align-content-center">
                <input type="submit" value="@(Model.StudentAllocationID == 0 ? "Add" : "Update")" class="btn btn-primary" style="font-size:14px;" />
                <button id="back-to-list" class="btn btn-secondary m-4" type="button" onclick="LoadList()">Back</button>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
      
        $('#subjectDropdown').change(function () {
            var subjectID = $(this).val();
            if (subjectID) {
                $.ajax({
                    url: '@Url.Action("GetTeachersBySubjectID", "Allocation")',
                    type: 'GET',
                    dataType: 'json',
                    data: { subjectID: subjectID },
                    success: function (response) {
                        //console.log("Teachers data:", response); 
                        if (response && Array.isArray(response.data)) {
                            $('#teacherDropdown').empty();
                            $('#teacherDropdown').append($('<option>').text('Select Teacher').attr('value', ''));

                            
                            $.each(response.data, function (index, teacher) {
                                //console.log("Teacher item:", teacher); 

                                $('#teacherDropdown').append($('<option>')
                                    .text(teacher.teacherRegNo + ' - ' + teacher.displayName) 
                                    .attr('value', teacher.subjectAllocationID)); 
                            });
                        } else {
                            console.error("Invalid response format or empty data array.");
                            $('#teacherDropdown').empty().append($('<option>').text('No teachers available').attr('value', ''));
                        }
                    },
                    error: function (xhr, status, error) {
                        console.error("Error retrieving teachers:", error);
                        $('#teacherDropdown').empty().append($('<option>').text('Error retrieving teachers').attr('value', ''));
                    }
                });
            } else {
                $('#teacherDropdown').empty().append($('<option>').text('Select Teacher').attr('value', ''));
            }
        });

        // Handle form submission
        $('#studentAllocationForm').submit(function (event) {
            event.preventDefault();

            var form = $(this);
            var serializedData = form.serialize();
            //console.log("Serialized Data:", serializedData); 

            $.ajax({
                type: form.attr('method'),
                url: form.attr('action'),
                data: serializedData,
                success: function (response) {
                    addStudentAllocationSuccess(response);
                },
                error: function (xhr, status, error) {
                    addStudentAllocationFailure(xhr, status, error);
                }
            });
        });
        $('.required').append('<span style="color: red">*</span>');

        // Handle teacher dropdown change
        $('#teacherDropdown').change(function () {
            var selectedValue = $(this).val();
           // console.log("Selected Value:", selectedValue);
            $('input[name="SubjectAllocationID"]').val(selectedValue); 
           // console.log("Input field value set to:", selectedValue); 
        });
    });
</script>

SMS_Stored/Views/Allocation/_StudentAllocationFilterView.cshtml
<div class="form-group filter">
    <label for="statusFilter" class="mt-2">Status:</label>
    <select id="filterStatus">
        <option value="all">All</option>
        <option value="active">Active</option>
        <option value="inactive">InActive</option>
    </select>
</div>

SMS_Stored/Views/Allocation/_StudentAllocationList.cshtml
@model IEnumerable<SMS.ViewModel.Allocation.StudentAllocationGroupedViewModel>

<div class="table-responsive">
    <table id="studentAllocationList" class="table table-bordered table-striped" style="text-align:center; width: 100%;">
        <thead style="text-align:center;">
            <tr>
                <th style="background-color: #cbf5ee; text-align: center;">Student Details</th>
                <th style="background-color: #cbf5ee; text-align: center;">Subject Details</th>
                <th style="background-color: #cbf5ee; text-align: center;">Teacher Details</th>
                <th style="background-color: #cbf5ee; text-align: center;">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var student in Model)
                {
                    var subjectCount = student.Subjects.Count();
                    foreach (var subject in student.Subjects)
                    {
                        var subjectDetail = $"{subject.SubjectCode} - {subject.SubjectName}";
                        
                        var teacherCount = subject.TeacherAllocations.Count();

                        var isFirstSubject = student.Subjects.IndexOf(subject) == 0;
                        var subjectRowspan = teacherCount;

                        foreach (var teacher in subject.TeacherAllocations)
                        {
                            <tr>
                                @if (isFirstSubject)
                                {
                                    <td rowspan="@subjectCount">
                                        @student.StudentRegNo - @student.DisplayName
                                        @if (student.IsEnable)
                                        {
                                        <span class="badge bg-success">Allocated</span>
                                        }
                                        else
                                        {
                                        <span class="badge bg-danger">Not Allocated</span>
                                        }
                                    </td>
                                }

                                @if (subject.TeacherAllocations.IndexOf(teacher) == 0)
                                {
                                    <td rowspan="@subjectRowspan">
                                        @subjectDetail
                                    </td>
                                }

                                <td>@teacher.TeacherRegNo - @teacher.DisplayName</td>
                                <td>
                                    <!-- Directly show delete icon for each teacher -->
                                    <a class="btn" style="background-color:#cbf5ee;" href="javascript:void(0);" onclick="Delete(@teacher.StudentAllocationID)">
                                        <i class="bi bi-trash" style="color:red;"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                }
            }
            else
            {
                <tr>
                    <td colspan="4">No records found.</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script>
    
</script>

SMS_Stored/Views/Allocation/_StudentAllocationSearchView.cshtml
@model SMS.ViewModel.Allocation.SearchViewModel


<form id="search" asp-action="" asp-controller="Allocation" method="get" class="search-container" style="margin-left:10px;">

    <select id="searchCategory" name="SearchCategory" asp-for="SearchCategory">
        <option value="DisplayName">Student Name</option>
        <option value="TeacherRegNo">Teacher Reg No</option>
        <option value="TeacherName">Display name</option>
        <option value="SubjectName">Subject Name</option>
        <option value="SubjectCode">Subject Code</option>
    </select>
    <input type="text" name="SearchText" id="customSearchBox" placeholder="Search..." asp-for="SearchText" />
</form>

SMS_Stored/Views/Allocation/_SubjectAllocationSearchView.cshtml
@model SMS.ViewModel.Allocation.SearchViewModel


<form id="search" asp-action="" asp-controller="Allocation" method="get" class="search-container" style="margin-left:10px;">
           
    <select id="searchCategory" name="SearchCategory" asp-for="SearchCategory">
                    <option value="TeacherRegNo">Teacher Reg No</option>
                    <option value="DisplayName">Display name</option>
                     <option value="SubjectCode">Last Name</option>
                    <option value="SubjectName">Subject Name</option>
                </select>
    <input type="text" name="SearchText" id="customSearchBox" placeholder="Search..." asp-for="SearchText" />
</form>

SMS_Stored/Views/Allocation/_UpsertTeacherSubjectAllocation.cshtml
@model SMS.Model.Teacher_Subject_Allocation.Teacher_Subject_AllocationBO
@{
    ViewBag.Title = "Upsert";
}
<link href="~/css/formstyle.css" rel="stylesheet" />

<form id="subjectAllocationForm" asp-action="UpsertSubjectAllocation" asp-controller="Allocation" method="post" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#createoredit">
    <div class="container d-flex justify-content-center align-items-center w-100 m-2" style="min-height: calc(100vh - 100px); margin-bottom: 50px;">
        <div class="card p-4 fr-div" style="max-width: 500px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1); border-radius: 10px;">
            @*<div class="col-md-12 ">*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.AntiForgeryToken()

            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.SubjectAllocationID)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row form-group d-flex">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.TeacherID, htmlAttributes: new { @class = "control-label required" })
                </div>
                <div class="col-md p-2">
                    @Html.DropDownListFor(model => model.TeacherID, ViewBag.TeacherList as SelectList, "Select Teacher", new { @class = "form-select", id = "teacherDropdown" })

                    @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })
                    <span id="teacherDropdownError" class="text-danger"></span>
                </div>
            </div>

            <div class="row form-group d-flex">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.SubjectID, htmlAttributes: new { @class = "control-label required" })
                </div>
                <div class="col-md p-2">
                    @Html.DropDownListFor(model => model.SubjectID, ViewBag.SubjectList as SelectList, "Select Subject", new { @class = "form-select", id = "subjectDropdown" })
                    @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group align-content-center">
                <input type="submit" value="@(Model.SubjectAllocationID== 0 ? "Add" : "Update")" class="btn btn-primary" style="font-size:14px;" />
                <button id="back-to-list" class="btn btn btn-secondary m-4" onclick="LoadList()">Back</button>
            </div>


        </div>
    </div>
</form>

@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script>
    $(document).ready(function () {
        // console.log("Hello");
        $('.required').append('<span style="color: red">*</span>');
    });
    $(document).ready(function () {
       

        $('#subjectAllocationForm').submit(function (event) {
            event.preventDefault();

            var form = $(this);
            $.ajax({
                type: form.attr('method'),
                url: form.attr('action'),
                data: form.serialize(),
                success: function (response) {
                    addSubjectAllocationSuccess(response);
                },
                error: function (xhr, status, error) {
                    addSubjectAllocationFailure(xhr, status, error);
                }
            });
        });
        //client side validation check
        // $('#studentRegNo').change(function () {
        //     var regNo = $(this).val();
        //     $.ajax({
        //         url: '@Url.Action("CheckStudentRegNoExists", "Student")',
        //         type: 'GET',
        //         data: { regNo: regNo },
        //         success: function (data) {
        //             if (data.exists) {
        //                 $('#regNoExistsMsg').text('Registration number already exists.');
        //             } else {
        //                 $('#regNoExistsMsg').text('');
        //             }
        //         },
        //         error: function () {
        //             $('#regNoExistsMsg').text('Error checking registration number.');
        //         }
        //     });
        // });
        // $('#studentDisplayName').change(function () {
        //     var displayName = $(this).val();
        //     $.ajax({
        //         url: '@Url.Action("CheckStudentDisplayNameExists", "Student")',
        //         type: 'GET',
        //         data: { displayName: displayName },
        //         success: function (data) {
        //             if (data.exists) {
        //                 $('#displayNameExistsMsg').text('Display Name already exists.');
        //             } else {
        //                 $('#displayNameExistsMsg').text('');
        //             }
        //         },
        //         error: function () {
        //             $('#displayNameExistsMsg').text('Error checking display name.');
        //         }
        //     });
        // });
       
    });

</script>