SMS_Stored/Controllers/LogController.cs
/// <summary>
///
/// </summary>
/// <author>Sadakshini</author>
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using SMS.BL.Log.Interface;
using SMS.Model.Log;
using SMS.ViewModel.ErrorResponse;
using SMS.ViewModel.Log;
using SMS.ViewModel.RepositoryResponse;
using SMS.ViewModel.StaticData;
using SMS.ViewModel.Student;


namespace SMS_Stored.Controllers
{
    public class LogController : Controller
    {

        private readonly ILogRepository _logRepository;
        public LogController(ILogRepository logRepository)
        {
            _logRepository = logRepository;
            
        }
        public IActionResult Index()
        {
           
            var viewModel = new LogViewModel
            {
                Logs= new List<LogBO>()
                
            };
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult GetLogs(FilterViewModel filterView)
        {
            var errorResponse = new ErrorResponse();
            try
            {
                var response = _logRepository.GetLogs(filterView);

                if (response.Success && response.Data != null && response.Data.Any())
                {
                   
                    var logCounts = response.Data
                        .GroupBy(log => log.Level) 
                        .Select(group => new LogLevelCountViewModel
                        {
                            LogLevel = group.Key,
                            Count = group.Count()
                        })
                        .ToList();

                    var viewModel = new LogViewModel
                    {
                        Logs = response.Data,
                        SearchView = new SearchViewModel(),
                        LogCounts = logCounts
                    };

                    return PartialView("_LogList", viewModel);
                }
                else
                {
                    errorResponse.Messages.Add(string.Format(string.Join(", ", response.Messages)));
                    return new JsonResult(errorResponse);
                }
            }
            catch
            {
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Logs"));
                return Json(new { success = false, message = errorResponse.Messages });
            }
        }


        public ActionResult SearchLogs(SearchViewModel model)
        {
            var errorResponse = new ErrorResponse();
            try
            {
                var response = _logRepository.SearchLogs(model);
                if (response.Success && response.Data != null && response.Data.Any())
                {
                    var viewModel = new LogViewModel
                    {
                        Logs = response.Data,
                        SearchView = new SearchViewModel()

                    };
                    return PartialView("_LogList", viewModel);
                }
                else
                {
                  
                    return Json(new { success = false, message = response.Messages });
                }

            }
            catch
            {
               
                errorResponse.Messages.Add(string.Format(StaticMessages.Data_Not_Found));
                // errorResponse.Messages.Add(ex.Message); 

                return Json(new { success = false, message = errorResponse.Messages });
            }
        }

        [HttpGet]
        public IActionResult GetLogCountsForChart(FilterViewModel filterView)
        {
            try
            {
                var response = _logRepository.GetLogs(filterView);

                if (response.Success && response.Data != null && response.Data.Any())
                {
                    var logCounts = response.Data
                        .GroupBy(log => log.Level) // Adjust 'Level' to your log level property
                        .Select(group => new
                        {
                            LogLevel = group.Key,
                            Count = group.Count()
                        })
                        .ToList();

                    return Json(logCounts);
                }
                else
                {
                    return Json(new { success = false, message = "No data available" });
                }
            }
            catch
            {
                return Json(new { success = false, message = "Error loading data" });
            }
        }
        /// <summary>
        /// /
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult GetDailyLogCounts(FilterViewModel filterView)
        {
            try
            {
                var logCounts = _logRepository.GetDailyLogCounts(filterView);

                if (logCounts != null && logCounts.Any())
                {
                    return Json(logCounts);
                }
                else
                {
                    return Json(new { success = false, message = "No data available" });
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { error = ex.Message });
            }
        }
        public IActionResult ExportToPdf(FilterViewModel filterView)
        {
            var response = _logRepository.GetLogs(filterView);
            var logs= response.Data;
            var logViewModel = new LogViewModel
            {
                Logs = logs,
                FilterView=filterView
               
            };
            return new ViewAsPdf("_LogListPdf", logViewModel)
            {
                FileName = $"LogList_{DateTime.Now:yyyyMMdd_HHmmss}.pdf",
                PageSize = Rotativa.AspNetCore.Options.Size.A4,
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait,
                CustomSwitches = "--disable-smart-shrinking --print-media-type --viewport-size 1280x1024"
            };

        }

    }
}

SMS_Stored/Controllers/StudentController.cs
/// <summary>
///
/// </summary>
/// <author>Sadakshini</author>
using System.Data;
using NLog;
using Microsoft.AspNetCore.Mvc;
using SMS.BL.Student.Interface;
using SMS.Model.Student;
using SMS.ViewModel.ErrorResponse;
using SMS.ViewModel.RepositoryResponse;
using SMS.ViewModel.StaticData;
using SMS.ViewModel.Student;
using System.Diagnostics.Eventing.Reader;
using ClosedXML.Excel;
using Rotativa.AspNetCore;
using System.Text.RegularExpressions;


namespace SMS_Stored.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;
        private readonly ILogger<StudentController>_logger;
        

        public StudentController(IStudentRepository studentRepository,ILogger<StudentController> logger)
        {
            _studentRepository = studentRepository;
            _logger = logger;
        }
        /// <summary>
        /// Index page view
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            _logger.LogInformation("Index page view requested");
            var viewModel = new StudentViewModel
            {
                StudentList = new List<StudentBO>(),
                SearchView = new SearchViewModel() 
            };
            return View(viewModel);
        }

        /// <summary>
        /// Get the student details
        /// </summary>
        /// <param name="status"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetStudents(string status = "all")
        {
            var errorResponse = new ErrorResponse();
            try
            {
                _logger.LogInformation("GetStudents method called with status:{ Status}", status);
                var response = new RepositoryResponse<IEnumerable<StudentBO>>();
                bool? isEnabled = null;
                if (status.ToLower() == "active")
                {
                    isEnabled = true;
                }
                else if (status.ToLower() == "inactive")
                {
                    isEnabled = false;
                }

                response = _studentRepository.GetStudents(isEnabled);

                if (response.Success && response.Data != null && response.Data.Any())
                {
                    var viewModel = new StudentViewModel
                    {
                        StudentList = response.Data,
                        SearchView = new SearchViewModel()

                    };
                    return PartialView("_StudentList", viewModel);
                }
                else
                {
                    errorResponse.Messages.Add(string.Format(response.Messages.ToString()));
                    return new JsonResult(errorResponse);
                }
            }
            catch 
            {
                _logger.LogError("Error occurred while getting students");
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Students"));

                return Json(new { success = errorResponse.Success, message = errorResponse.ErrorMessages });
            }
        }

        /// <summary>
        /// add or edit student details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult UpsertStudent(long id = 0)
        {
            if (id == 0)
            {
                _logger.LogInformation("UpsertStudent method called to add a new Student");
                return PartialView("_Upsert", new StudentBO());
            }
            else
            {
                // Edit existing student
                _logger.LogWarning("UpsertStudent method called to edit student with ID: {ID}", id);
                var response = _studentRepository.GetStudentByID(id);
                if (!response.Success || response.Data == null)
                {
                    return NotFound();
                }
                return PartialView("_Upsert", response.Data);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpsertStudent(StudentBO student)
        {
            var errorResponse = new ErrorResponse();
            try
            {
                var response = new RepositoryResponse<bool>();
                response = _studentRepository.UpsertStudent(student);

                if (response.Success)
                {
                    return Json(new { success = true, message = response.Messages });
                   
                }
                else
                {
                    _logger.LogError("User attempt to submit form without filling necessary fields or existence data");
                    return Json(new { success = false, message = response.Messages });
                }
            }
            catch(Exception ex)
            {
                
                errorResponse.Messages.Add(string.Format(StaticMessages.Fill_Form));
                _logger.LogError(ex, "An error occurred while add or edit a student ");
                return Json(new { success = errorResponse.Success, message = errorResponse.ErrorMessages });
            }
        }



        /// <summary>
        /// delete the student details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteStudent(long id)
        {
            var errorResponse = new ErrorResponse();
           
           // bool requiresConfirmation;
            try
            {
                _logger.LogInformation("Delete Student method called to delete student with ID: {ID}", id);
                var response = new RepositoryResponse<bool>();
               // string message;

                response = _studentRepository.DeleteStudent(id);

                if (response.Success)
                {
                    return Json(new { success = true, message = response.Messages });
                }
                else
                {
                    _logger.LogWarning("Delete method called to delete student with ID: {ID}", id);
                    
                    return Json(new { success = false,  message = response.Messages });
                }

            }
            catch 
            {
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Students"));

                return Json(new { success = errorResponse.Success, message = errorResponse.ErrorMessages });
            }
        }

        /// <summary>
        /// check the existence of registration number
        /// </summary>
        /// <param name="regNo"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult CheckStudentRegNoExists(string regNo)
        {
            var errorResponse = new ErrorResponse();
            try
            {
                _logger.LogDebug("Checked the registration number existence");
                var response = _studentRepository.DoesStudentRegNoExist(regNo);

                if (response.Success)
                {
                    
                    return Json(new { exists = response.Data });
                }
                else
                {
                    _logger.LogError("The registration number entered is alredy exists.");
                    return Json(new { success = false, message = response.Messages });
                }
            }
            catch (Exception ex)
            {
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Student Registration Number"));
                _logger.LogError(ex, "An error occurred while checking the registration number: {regNo}", regNo);

                return Json(new { success = false, message = errorResponse.Messages, exception = ex.Message });
            }
        }

        /// <summary>
        /// check the existence of display name
        /// </summary>
        /// <param name="displayName"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult CheckStudentDisplayNameExists(string displayName)
        {
            var errorResponse= new ErrorResponse();
            try
            {
                _logger.LogDebug("Checked the display name existence");
                var response = _studentRepository.DoesStudentDisplayNameExist(displayName);
                if (response.Success)
                {
                    _logger.LogDebug("Checked the display name existence");
                    return Json(new { exists = response.Data });
                }
                else
                {
                    _logger.LogWarning("The display name entered is alredy exists.");
                    return Json(new { success = false, message = response.Messages });
                }
            }
            catch (Exception ex)
            {
                errorResponse.Messages.Add(string.Format(StaticMessages.Error_Load_Data, "Student Display name"));
                errorResponse.Messages.Add(ex.Message); 

                return Json(new { success = false, message = errorResponse.Messages });
            }
        }
        /// <summary>
        /// Check the existence of emial id
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult CheckStudentEmailExists(string email)
        {
            var errorResponse = new ErrorResponse();
            try
            {
                _logger.LogDebug("Checked the Email Id existence");
                var response = _studentRepository.DoesStudentEmailExist(email);
                if (response.Success)
                {
                    
                    return Json(new { exists = response.Data });
                }
                else
                {

SMS_Stored/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SMS_Stored.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/smoothness/jquery-ui.css">

    <link href="https://cdn.datatables.net/2.0.7/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">SMS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subject</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Log" asp-action="Index">Logs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Allocation" asp-action="SubjectAllocation">Subject_Allocation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Allocation" asp-action="StudentAllocation">Student_Allocation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid body-content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="container-fluid border-top  text-dark >
        <div class="footer text-center" style="background-color: #658cc2;">
            &copy; 2024 - SMS_Stored 
        </div>
    </footer>


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
   @*  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
 *@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>


    <!-- jQuery UI -->

    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>


    <!-- DataTables Bootstrap Integration -->
    <script src="https://cdn.datatables.net/2.0.7/js/dataTables.bootstrap5.min.js"></script>

    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   

    <!-- Include DataTables JS -->
    @*    <script src="c:\users\acer\.nuget\packages\datatables.net\2.0.8\contentfiles\any\any\wwwroot\js\datatables.min.js"></script> *@

   @*  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@

    @*  <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script> *@

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>